#!/bin/bash

# bashrc

[ -n "$PS1" ] && source ~/.bash_profile


export NVM_DIR="/Users/junkycoder/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

#export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# https://www.npmjs.com/package/eslint-config-airbnb
#(
#  export PKG=eslint-config-airbnb;
#  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
#)
