#!/bin/bash

# bash_aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="ls -1G"
# Order by last modified, long form no user group, color
#alias lt="ls -t1G"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGF1h"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGF1th"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# Open file in existing MacVim window
alias gvim="open -a MacVim"
alias mvim="open -a MacVim"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
alias flushdns="dscacheutil -flushcache"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# Git shortcuts
alias gs="git status"
alias gs='git status '
alias gp='git pull'
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gca='git commit --amend'
alias gcf='git commit --fixup=HEAD'
alias gra='git rebase -i --autosquash'
alias gd='git diff'
alias go='git checkout '
alias gl='git --no-pager log -10 --oneline --decorate --graph'
alias gll='git --no-pager log --oneline --decorate --graph'
# Misspells git aliases
alias got='git '

# Local tunnel tools
alias ng='~/src/ngrok '

# Search for content in files
alias gr='grep -I --exclude-dir=node_modules -rn '

# React Native shortcut
alias rn='react-native '

alias ipl="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"